### ISSUE TITLE
[Feature] Adding support for Cartographer firmware

### ISSUE THREAD

**Issue by WizardPC** [fbeauKmi/update_klipper_and_mcus#12]
Will it be possible to add support of Cartographer firmware update in UKAM ?

Since it's CAN bus and an MCU : https://docs.cartographer3d.com/cartographer-probe/firmware/firmware-updating/via-katapult/canbus-flash

Thanks !

**Comment by fbeauKmi** [comment]
Hello , thanks for your interest in UKAM.

As far as I know, Cartographer uses its own prebuilt firmwares. The script used to update the board seems really well done and pretty reliable.  

At this stage, I don't know how to add benefits to support for externally built firmware (not only Cartographer) .
Maybe a link to an external script in mcus.ini, but I'm not sure about that idea.

I let this issue open for further comments.

**Comment by krautech** [comment]
Hiya 👋🏼

I really need to install this, almost went to create my own version.. but now I don't have to reinvent the wheel.

I'm the guy who wrote the Cartographer firmware flasher and currently in the process of rewriting it in python.

I am going to add a bunch of python args so that if you know the device id (UUID or serial) and you put the --latest arg, it will flash the cartographer with the latest available firmware via Katapult.

So happy to work with you if this is something you'd be interested in.

**Comment by fbeauKmi** [comment]
Hello,

Glad to see you here, any help is welcome. I will probably make some adjustments in the next few weeks in order to use these external firmware.

Ideally, it would be good to get the version of the next firmware.
I had listed 3 modules that require special firmware (cartographer, beacon, roadrunner, ...) But there are probably more now, I'm not very involved in the 3D printing community at the moment.

Thanks for the proposal.

**Comment by krautech** [comment]
Works great! I made a ton of changes to the firmware.py script to streamline this process and a bunch of other small fixes so once I get those out, this will work great

![image](https://github.com/user-attachments/assets/52424de2-09d2-4c35-9b60-46272493ae46)
